---
- name: Copy the files from server1 to server2
  #  hosts: ansible-node2-rhel76
  hosts: all
  become: yes
  vars:
    - file_name: file1.txt
  tasks:
    - name: First get the required file from source to tower
      fetch:
        src: /tmp/file1.txt
        dest: /tmp/
        flat: yes

