---
- name: Identify and cleatr the sticky bit
  hosts: all
  become: yes
  vars:
    given_dir_path: 
      - /tmp/sticky_bit_dir
      - /tmp/sticky_bit_dir2
  tasks:
    - name: Create sticky bit directories
      file:
        path: "{{item}}"
        state: directory
        mode: '1755'
      register: created_dir
      loop: "{{given_dir_path}}"

    - name: sticky bit directory presence now
      shell:
        "ls -ld {{item}}"
      loop: "{{given_dir_path}}"
      register: permission


    - name: Remove the sticky bit permission
      shell:
        "chmod 0755 {{item}}"
      register: permission_after
      loop: "{{given_dir_path}}"


    - name: Display the permission after change
      shell:
        "ls -ld {{item}}"
      register: permission_after
      loop: "{{given_dir_path}}"

    - name: debug the loop
      debug:
        var: permission_after



    - name: debug the after permission
      debug:
        msg: "The dir permission after the chnage is: {{item.stdout}}"
      with_items: permission_after['results']
