---
- name: Copy a file from git to remote with tower survey
  hosts: all
  become: yes
  ignore_errors: yes
  vars:
    var1: OK
  tasks:
    - name: copy a file from git to target server
      copy:
        src: test.txt
        dest: /etc/facts2_txt.txt
        mode: '0644'
      when: "'OK' in var1"
