---
- name: test
  hosts: all
  ignore_errors: yes
  vars:
          #server_name:
          # - srv1: "{{server_fqdn}}"
          # dirpath: "{{path_list}}"
                # - "{{cmd_path}}"
                # - 'chmod 0755 /tmp/sticky_bit_dir'
                # - 'chmod 0755 /tmp/sticky_bit_dir2'
                # - 'chmod 0755 /tmp/sticky_bit_dir100'
          # - srv1: ansible-node2-rhel76
            # dirpath:
            # - 'chmod 0755 /tmp/sticky_bit_dir'
            # - 'chmod 0755 /tmp/sticky_bit_dir2'
            # - 'chmod 0755 /tmp/sticky_bit_dir3'
    given_dir_path:
      - /tmp/sticky_bit_dir1
        /tmp/sticky_bit_dir2
        /tmp/sticky_bit_dir3
        /tmp/sticky_bit_dir4
        /tmp/sticky_bit_dir5
        /tmp/sticky_bit_dir6
        /tmp/sticky_bit_dir7
 

  tasks:
    - name: Just Print a hallo
      debug:
        msg: "This message from {{ansible_hostname}}"

        #    - name: Create sticky bit directories
        # file:
        # path: "{{item}}"
        # state: directory
        # mode: '1755'
        # register: created_dir
        # loop: "{{given_dir_path}}"

    - name: Display the permission before the change
      shell:
        "ls -ld {{item.1}}"
      register: permission_before
      #delegate_to: "{{item.0.srv1}}"
      delegate_to: "{{item.0.srv1}}"
      with_subelements:
        - "{{server_name}}"
        - dirpath
          # - name: read the permission
          # debug:
          # var: permission_before
    - name: reading variable
      debug:
        var: permission_before

    - name: Read the permission after as message
      debug:
        msg: "{{permission_before | json_query('results[*].stdout')}}"

    - name: apply the command
      shell:
        "chmod o-w {{item.1}}"
      delegate_to: "{{item.0.srv1}}"
      with_subelements:
        - "{{server_name}}"
        - dirpath

    - name: Display the permission after the change
      shell:
        "ls -ld {{item.1}}"
      register: permission_after
      delegate_to: "{{item.0.srv1}}"
      with_subelements:
        - "{{server_name}}"
        - dirpath

    - name: read the variable
      debug:
        var: permission_after

    - name: Read the permission before as message
      debug:
        msg: "{{permission_before.results|map(attribute='item')|list|unique}}"

    - name: Read the permission after as message
      debug:
        msg: "{{permission_before | json_query('results[*].item')}}"

        # delegate_to: "{{item.0.srv1}}"
        # with_subelements:
        # - "{{server_name}}"
        # - dirpath


    - name: Read the permission after as message
      debug:
        msg: "{{permission_after | json_query('results[*].stdout')}}"
        # delegate_to: "{{item.0.srv1}}"
        # with_subelements:
        # - "{{server_name}}"
        # - dirpath

  
